id = "todo-tree"
name = "Todo tree "
version = "0.0.1"
schema_version = 1
authors = ["Angelator312 <angelator312@angelator312.top>"]
description = "Extension that adds todo tree on the sidebar"
repository = "https://github.com/your-name/my-zed-extension"


[slash_commands.echo]
description = "echoes the provided input"
requires_argument = true

[slash_commands.pick-one]
description="pick-one"
requires_argument=true
